/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.2/userguide/building_java_projects.html
 */


application {
    // Define the main class for the application.
    // Extension configuration block
    mainClass.set("kotlin.gradle.Core")
    applicationDefaultJvmArgs = listOf("-Xmx4m")
}
